[dark]
# Spicetify
text               = d4be98
subtext            = d4be98
main               = 282828
main-elevated      = 32302f
highlight          = 3c3836
highlight-elevated = 45403d
sidebar            = 1b1b1b
player             = 1b1b1b
card               = 32302f
shadow             = 1b1b1b
selected-row       = 45403d
button             = d8a657
button-active      = e78a4e
button-disabled    = 7c6f64
tab-active         = 32302f
notification       = 32302f
notification-error = ea6962
equalizer          = 000000
misc               = 45403d

# Gruvbox Material
red                = ea6962
orange             = e78a4e
yellow             = d8a657
green              = a9b665
aqua               = 89b482
blue               = 7daea3
purple             = d3869b
grey               = 928374
grey1              = 7c6f64
grey2              = a89984
bg_dim             = 1b1b1b
bg3                = 45403d
bg5                = 5a524c
fg1                = ddc7a1


[light]
# Spicetify
text               = 654735
subtext            = 654735
main               = fbf1c7
main-elevated      = f2e5bc
highlight          = eee0b7
highlight-elevated = e5d5ad
sidebar            = f3eac7
player             = f3eac7
card               = f2e5bc
shadow             = f3eac7
selected-row       = e5d5ad
button             = b47109
button-active      = c35e0a
button-disabled    = a89984
tab-active         = f2e5bc
notification       = f2e5bc
notification-error = c14a4a
equalizer          = 000000
misc               = e5d5ad

# Gruvbox Material
red                = c14a4a
orange             = c35e0a
yellow             = b47109
green              = 6c782e
aqua               = 4c7a5d
blue               = 45707a
purple             = 945e80
grey               = 928374
grey1              = a89984
grey2              = 7c6f64
bg_dim             = f3eac7
bg3                = e5d5ad
bg5                = dac9a5
fg1                = 514036
